### ISSUE TITLE
COB data off-center in Pebble Time Round

### ISSUE THREAD

**Issue by elnjensen** [ELUTE/PebbleSkyCgm#6]
When pulling COB data from Nightscout, the number is off center from the circle, displaced downward - see attached image.  It looks roughly as if the lower baseline edge of the text is aligned with the lower edge of the circle, rather than being centered. 

Happy to poke around in the code (though I don't have Pebble devel experience) if you have suggestions of where to look / what to look for. 

![fullsizerender](https://cloud.githubusercontent.com/assets/2545845/17630803/fa56ea24-608e-11e6-9127-b52ac00914b2.jpg)

**Comment by elnjensen** [comment]
By the way, probably unrelated to this issue, but I've wondered: you can see in the shot above that the right-hand part of the upper blue bar says "12:21", indicating that the data are 1 minute old.  Most of the time that shows "1m", "2m", etc. (number of minutes since last update) but sometimes it shows the time instead, and I haven't been able to figure out the pattern there.

**Comment by ELUTE** [comment]
I cannot see a picture but I have a fix for the alignment and am looking into the other issue.

**Comment by elnjensen** [comment]
OK, thanks!  Weird about the picture- I can see it on github.com whether or not I'm logged in.  But sounds like you know what issue I mean anyway.  Thanks for all of your work on this.

**Comment by ELUTE** [comment]
resolved
